# Generated by Django 4.1.7 on 2023-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
