# Generated by Django 5.2.5 on 2025-08-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_alter_empleados_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiosCopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sorteo', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.empleados')),
            ],
        ),
    ]
